### ISSUE TITLE
Role management

### ISSUE THREAD

**Issue by silvibiblio** [CRISalid-esr/SoVisuPlus#51]
Not authenticated user : he just access the login page 
Self editor user : he can edit just his own data
Editor with perimeter : he can edit just data concerning his own perimeter
Editor without perimeter : user that can edit whatever data of the applcaition
Admin : he has all the rights on the application

**Comment by jdp1ps** [comment]
We don’t need so detailed roles (self editor, restricted editor, unrestricted editor, etc.) as we will use polymorphic scopes to control where the permissions apply. A polymorphic permission scope can target :
- a Person (self or delegated individual),
- a ResearchStructure (e.g. "UMR 12345", or even a team inside a research unit) 
- an Institution ("École des Beaux-Arts", or event an institution grouping other institutions)
- an InstitutionDivision

This lets us express “self”, “restricted”, and “unrestricted” without exploding the number of roles.
e.g. A self-editor role is an editor role scoped to a person, the user himself.

A person may combine several roles. The role configuration file does not contain scopes, as these will be defined at runtime when roles are assigned to individuals (user_role is a ternary relationship: user - role - scope).

Role config file example : 

```
roles:
  - name: admin
    system: true
    description: Full access
    permissions:
      - action: manage
        subject: all

  - name: document_editor
    description: Edit document metadata (scope determines reach)
    permissions:
      - action: update
        subject: Document
        fields: [titles, abstracts, contributors, identifiers]

  - name: document_merger
    description: Merge / unmerge documents and source records
    permissions:
      - action: merge
        subject: Document
      - action: unmerge
        subject: DocumentRecord

```
